### ISSUE TITLE
egcd error?

### ISSUE THREAD

**Issue by zhuce2022** [RsaCtfTool/RsaCtfTool#306]
system: win10 wsl2 ubuntu18.04
run:xx@xx:/mnt/d/Code/python/RsaCtfTool-master$ python3 RsaCtfTool.py
`
Traceback (most recent call last):
  File "RsaCtfTool.py", line 20, in <module>
    from lib.rsa_attack import RSAAttack
  File "/mnt/d/Code/python/RsaCtfTool-master/lib/rsa_attack.py", line 6, in <module>
    from lib.keys_wrapper import PublicKey, PrivateKey
  File "/mnt/d/Code/python/RsaCtfTool-master/lib/keys_wrapper.py", line 12, in <module>
    from lib.conspicuous_check import privatekey_check
  File "/mnt/d/Code/python/RsaCtfTool-master/lib/conspicuous_check.py", line 1, in <module>
    from lib.rsalibnum import is_prime, isqrt, gcd, lcm, getpubkeysz, invert
  File "/mnt/d/Code/python/RsaCtfTool-master/lib/rsalibnum.py", line 10, in <module>
    from egcd import egcd
  File "/home/xx/.local/lib/python3.6/site-packages/egcd/__init__.py", line 2, in <module>
    from egcd.egcd import egcd
  File "/home/xx/.local/lib/python3.6/site-packages/egcd/egcd.py", line 5
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
`

vmware ubuntu 18.04
run python3 RsaCtfTool.py
`
Traceback (most recent call last):
  File "RsaCtfTool.py", line 20, in <module>
    from lib.rsa_attack import RSAAttack
  File "/home/xxx/rsa/RsaCtfTool-master/lib/rsa_attack.py", line 6, in <module>
    from lib.keys_wrapper import PublicKey, PrivateKey
  File "/home/xxx/rsa/RsaCtfTool-master/lib/keys_wrapper.py", line 12, in <module>
    from lib.conspicuous_check import privatekey_check
  File "/home/xxx/rsa/RsaCtfTool-master/lib/conspicuous_check.py", line 1, in <module>
    from lib.rsalibnum import is_prime, isqrt, gcd, lcm, getpubkeysz, invert
  File "/home/xxx/rsa/RsaCtfTool-master/lib/rsalibnum.py", line 10, in <module>
    from egcd import egcd
  File "/home/xxx/.local/lib/python3.6/site-packages/egcd/__init__.py", line 2, in <module>
    from egcd.egcd import egcd
  File "/home/xxx/.local/lib/python3.6/site-packages/egcd/egcd.py", line 5
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
`

download https://pypi.org/project/egcd/#files and install 
There are still mistakes

**Comment by daedalus** [comment]
Hi, are you using the last version of the repo? I suggest you to clone it with git clone...

**Comment by daedalus** [comment]
This bug doesn't apply anymore.
