### ISSUE TITLE
Small Fraction ZeroDivisionError

### ISSUE THREAD

**Issue by kk-kd** [RsaCtfTool/RsaCtfTool#333]
I was trying to verify my installation and used the numbers in README.  The small fraction attack raised an error and the program was terminated. 

````bash
$ ./RsaCtfTool.py -n 1078615880917389544637583114473414840170786187365383943640580486946396054833005778796250863934445216126720683279228360145952738612886499734957084583836860500440925043100784911137186209476676352971557693774728859797725277166790113706541220865545309534507638851540886910549436636443182335048699197515327493691587 --attack all -e
10000
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmp9ttz8kla.
[*] Performing smallfraction attack on /tmp/tmp9ttz8kla.
Traceback (most recent call last):
  File "/home/kd/tools/RsaCtfTool/./RsaCtfTool.py", line 430, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/kd/tools/RsaCtfTool/lib/rsa_attack.py", line 304, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/home/kd/tools/RsaCtfTool/attacks/single_key/smallfraction.py", line 30, in attack
    priv_key = PrivateKey(
  File "/home/kd/tools/RsaCtfTool/lib/keys_wrapper.py", line 111, in __init__
    self.d = int(invert(e, self.phi))
ZeroDivisionError: invert() no inverse exists
```

**Comment by daedalus** [comment]
Hi e should be prime and coprime to whatever phi is, if you pick a composite e it should fail because e and phi share some prime factors in common.

**Comment by kk-kd** [comment]
Right. I just noticed that the error was not properly handled. When running all attacks, the exception terminated the program before some other attacks get a chance to run. 

Can I open a small PR that catches all unhandled exceptions?

**Comment by daedalus** [comment]
Please do feel welcome to send a PR if you like
