### ISSUE TITLE
How to fix it

### ISSUE THREAD

**Issue by pitaya-Toby** [RsaCtfTool/RsaCtfTool#356]
Traceback (most recent call last):
  File "/root/RsaCtfTool/RsaCtfTool.py", line 20, in <module>
    from lib.rsa_attack import RSAAttack
  File "/root/RsaCtfTool/lib/rsa_attack.py", line 6, in <module>
    from lib.keys_wrapper import PublicKey, PrivateKey
  File "/root/RsaCtfTool/lib/keys_wrapper.py", line 12, in <module>
    from lib.conspicuous_check import privatekey_check
  File "/root/RsaCtfTool/lib/conspicuous_check.py", line 1, in <module>
    from lib.number_theory import is_prime, isqrt, gcd, lcm, getpubkeysz, invert
ModuleNotFoundError: No module named 'lib.number_theory'

**Comment by daedalus** [comment]
You need to fetch the last commit.
