### ISSUE TITLE
NameError: name 'gmpy2' is not defined. Did you mean: 'gmpy'?-------kali-2022.03

### ISSUE THREAD

**Issue by jackjwang** [RsaCtfTool/RsaCtfTool#382]
# python3 RsaCtfTool.py 
Traceback (most recent call last):
  File "/root/RsaCtfTool/RsaCtfTool.py", line 20, in <module>
    from lib.rsa_attack import RSAAttack
  File "/root/RsaCtfTool/lib/rsa_attack.py", line 6, in <module>
    from lib.keys_wrapper import PublicKey, PrivateKey
  File "/root/RsaCtfTool/lib/keys_wrapper.py", line 12, in <module>
    from lib.conspicuous_check import privatekey_check
  File "/root/RsaCtfTool/lib/conspicuous_check.py", line 1, in <module>
    from lib.number_theory import is_prime, isqrt, gcd, lcm, getpubkeysz, invert
  File "/root/RsaCtfTool/lib/number_theory.py", line 306, in <module>
    is_divisible = gmpy2.is_divisible
NameError: name 'gmpy2' is not defined. Did you mean: 'gmpy'?

**Comment by daedalus** [comment]
Solved in [3efa316](https://github.com/RsaCtfTool/RsaCtfTool/commit/3efa3164273c3865782a6da2e6eff2785fbf0e72)
