### ISSUE TITLE
UnboundLocalError: local variable 'selected_attacks' referenced before assignment

### ISSUE THREAD

**Issue by jaschr** [RsaCtfTool/RsaCtfTool#388]
[*] Testing key /tmp/tmp7xop7353.
Traceback (most recent call last):
  File "/home/jacob/tools/RsaCtfTool/RsaCtfTool.py", line 494, in <module>
    main()
  File "/home/jacob/tools/RsaCtfTool/RsaCtfTool.py", line 488, in main
    args = run_attacks(args, logger)
  File "/home/jacob/tools/RsaCtfTool/RsaCtfTool.py", line 226, in run_attacks
    attackobj.attack_single_key(publickey, selected_attacks)
UnboundLocalError: local variable 'selected_attacks' referenced before assignment

This while passing flags -n  -e --uncipher

**Comment by pathefone** [comment]
got the same error

**Comment by Ladykilljoy** [comment]
I have the exact same error
