### ISSUE TITLE
Cannot get past Python Errors

### ISSUE THREAD

**Issue by redeyehal** [RsaCtfTool/RsaCtfTool#392]
Ran this in Parrot (similar issues with Kali)

$python3 RsaCtfTool.py --attack cm_factor --publickey key.pub --private

and I cannot get past all the output errors to get a successful run.

`*] Testing key key.pub.
[*] Performing cm_factor attack on key.pub.
 17%|███████▌                                     | 1/6 [00:01<00:05,  1.10s/it][!] Timeout.
 17%|███████▌                                     | 1/6 [00:59<04:59, 60.00s/it]
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/donald/Hackthebox/WeakRSA/RsaCtfTool/lib/rsa_attack.py", line 314, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/donald/Hackthebox/WeakRSA/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/donald/Hackthebox/WeakRSA/RsaCtfTool/attacks/single_key/cm_factor.py", line 23, in attack
    sageresult = subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1981, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/donald/Hackthebox/WeakRSA/RsaCtfTool/lib/utils.py", line 198, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

Traceback (most recent call last):
  File "/home/donald/Hackthebox/WeakRSA/RsaCtfTool/RsaCtfTool.py", line 491, in <module>
    main()
  File "/home/donald/Hackthebox/WeakRSA/RsaCtfTool/RsaCtfTool.py", line 485, in main
    args = run_attacks(args, logger)
  File "/home/donald/Hackthebox/WeakRSA/RsaCtfTool/RsaCtfTool.py", line 223, in run_attacks
    attackobj.attack_single_key(publickey, selected_attacks)
  File "/home/donald/Hackthebox/WeakRSA/RsaCtfTool/lib/rsa_attack.py", line 340, in attack_single_key
    self.print_results_details(publickey)
  File "/home/donald/Hackthebox/WeakRSA/RsaCtfTool/lib/rsa_attack.py", line 99, in print_results_details
    print_results(self.args, publickeyname, self.priv_key, self.unciphered)
  File "/home/donald/Hackthebox/WeakRSA/RsaCtfTool/lib/utils.py", line 79, in print_results
    if any(
TypeError: any() takes exactly one argument (3 given)
`

I'm not sure what information you need but let me know and I can post OS versions, Python version, etc.

Thank you

**Comment by daedalus** [comment]
It seems that you don't have sage installed

**Comment by daedalus** [comment]
@MarcoMeinardi can you try to workout what is failing here, I think it may be related to the latest push.
Thanks

**Comment by MarcoMeinardi** [comment]
Yes, that is my bad, I forgot to add parenthesis in the any/all calls, sorry.
Skaft has already fixed it, I'm going to double check it later

**Comment by daedalus** [comment]
Merged and fixed.
