### ISSUE TITLE
Error when trying to uncipher given a : n, e

### ISSUE THREAD

**Issue by guilhas07** [RsaCtfTool/RsaCtfTool#397]
When trying to uncipher with this command:
 `python3 ./RsaCtfTool/RsaCtfTool.py -n n_value -e 65537 --uncipher cypher_value`
 It gives me this error. The same happens if I dump the public key first and use it to uncypher.
 Am I doing something wrong?
```  
[*] Testing key /tmp/tmpeyox0wqx.
attack initialized...
attack initialized...
[*] Performing factordb attack on /tmp/tmpeyox0wqx.
[*] Attack success with factordb method !
Traceback (most recent call last):
  File "RsaCtfTool/RsaCtfTool.py", line 499, in <module>
    main()
  File "RsaCtfTool/RsaCtfTool.py", line 493, in main
    args = run_attacks(args, logger)
  File "RsaCtfTool/RsaCtfTool.py", line 229, in run_attacks
    attackobj.attack_single_key(publickey, selected_attacks)
  File "RsaCtfTool/lib/rsa_attack.py", line 356, in attack_single_key
    tmin, tmax, tavg = min(T), max(T), sum(T) / len(T)
ValueError: min() arg is an empty sequence
```

**Comment by daedalus** [comment]
What values contain n_value and cypher_value in `python3 ./RsaCtfTool/RsaCtfTool.py -n n_value -e 65537 --uncipher cypher_value`?
at face value it seems to be wrong.

**Comment by guilhas07** [comment]
They are all numbers. I didn't want to put them here because of their size.

**Comment by daedalus** [comment]
can you share them in a pastebin?

**Comment by guilhas07** [comment]
Sure: https://pastebin.com/Xezwj7H1 . It is worth mentioning that I see this error on some of the tests when running the RsaCtfTool test.sh script.

**Comment by daedalus** [comment]
Works like a charm for me, try with the latest commits.
Btw is worth mentioning that the test.sh file is being deprecated.

```
dclavijo@whiskey:~/RsaCtfTool$ python3 RsaCtfTool.py -n 1280...3923 -e 65537 --uncipher 6232...2021
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmprnevrz4s.
attack initialized...
attack initialized...
[*] Performing fibonacci_gcd attack on /tmp/tmprnevrz4s.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9999/9999 [00:00<00:00, 172401.96it/s]
[+] Time elapsed: 0.1379 sec.
[*] Performing system_primes_gcd attack on /tmp/tmprnevrz4s.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7007/7007 [00:00<00:00, 645951.21it/s]
[+] Time elapsed: 0.0585 sec.
[*] Performing smallq attack on /tmp/tmprnevrz4s.
[+] Time elapsed: 0.4913 sec.
[*] Performing mersenne_primes attack on /tmp/tmprnevrz4s.
 24%|███████████████████████████████████                                                                                                                  | 12/51 [00:00<00:00, 173557.41it/s]
[+] Time elapsed: 0.0009 sec.
[*] Performing pastctfprimes attack on /tmp/tmprnevrz4s.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 113/113 [00:00<00:00, 647481.36it/s]
[+] Time elapsed: 0.0008 sec.
[*] Performing factordb attack on /tmp/tmprnevrz4s.
[*] Attack success with factordb method !
[+] Total time elapsed min,max,avg: 0.0008/0.4913/0.1379 sec.

Results for /tmp/tmprnevrz4s:

Unciphered data :
HEX : 0x007069636f4354467b736d6131315f4e5f6e305f67306f645f30353031323736377d
INT (big endian) : 13016382529449106065927291425342535437996222135352905256639555654677400177227645
INT (little endian) : 3711739942918996135095564070444078210974633154646265969428826141271237837554544640
utf-8 : picoCTF{sma11_N_n0_g0od_05012767}
utf-16 : 瀀捩䍯䙔獻慭ㄱ也湟弰で摯た〵㈱㘷紷
STR : b'\x00picoCTF{sma11_N_n0_g0od_05012767}'
```

**Comment by guilhas07** [comment]
It now works with the latest commits ! Thank you!
