### ISSUE TITLE
NameError: name 'common_modulus' is not defined

### ISSUE THREAD

**Issue by BaronSam3di** [RsaCtfTool/RsaCtfTool#403]
Hi Team

Thanks for this tool. Im brand new to it but wanted to try it on a htb Weak Rsa challenge. 
Steps as followed on Mac OS ventura and `Linux kali 5.18.0-kali5-amd64 #1 SMP PREEMPT_DYNAMIC Debian 5.18.5-1kali6 (2022-07-07) x86_64 GNU/Linux` produce same error.

- Downloaded git repo
- ran `pip3 install -r "Requirements.txt"`
- ran `python3 setup.py install`
- ran `python3 RsaCtfTool.py --help`

```sh
Traceback (most recent call last):
  File "/root/Tools/RsaCtfTool/RsaCtfTool.py", line 20, in <module>
    from lib.rsa_attack import RSAAttack
  File "/root/Tools/RsaCtfTool/lib/rsa_attack.py", line 7, in <module>
    from lib.keys_wrapper import PublicKey, PrivateKey
  File "/root/Tools/RsaCtfTool/lib/keys_wrapper.py", line 12, in <module>
    from lib.conspicuous_check import privatekey_check
  File "/root/Tools/RsaCtfTool/lib/conspicuous_check.py", line 1, in <module>
    from lib.number_theory import is_prime, gcd, lcm, getpubkeysz, invert
  File "/root/Tools/RsaCtfTool/lib/number_theory.py", line 585, in <module>
    common_modulus,
NameError: name 'common_modulus' is not defined
```

Am I missing something? Many thanks

**Comment by daedalus** [comment]
Solved
