### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by johntrigg** [RsaCtfTool/RsaCtfTool#413]
Making and launching a virtual enviroment, and then running it, and then trying to install the requirements.txt generates the following error:

```
Building wheels for collected packages: gmpy2, factordb-pycli
  Building wheel for gmpy2 (setup.py) ... error
  error: subprocess-exited-with-error
```

Also, even when installing everything manually, it does not work, due to the following error: AttributeError: 'PrivateKey' object has no attribute 'filename'

The command I used was:

```
python RsaCtfTool.py -n 14984962198660063864382329332414420640383401076210940326970380580002686792787549841757826322207380228475709831526150079054985643220286460040858635679099522461047125435547179836262035088538613643864726343947555810131214032176684953210400649987009365195363305448984625056469651901622510492256805277916429238237678991624609211686866220638957573492408427673564762335476393937949771790288899651982610955789425606231334241253290222180270938067127910825221018045967093881137664435200297802313731449759678431791478785781663312163425434957456894805128431979105321354657985616047053485527175910574195011390399363690121273756133 --uncipher 6768104913683895415526939045370590550117554920225156260379702730027550103436992098353630848682338632904020105190926576422415271335297087322016662525595856010107474446532478159170598027866086590558243703091255513088663109170531701124458287463627379967135605546224149155819285207823433321409257025446269419078160207003575826357719547000406426784859828102165453909838062799506309448595724046503160186280321813546290568120114314149514552243567398093040978961861254125092135488581072054559190418120161813924592848661725498460645649142740905294524721435342632718169679652876154756570559230965212369531118067468874085691460
```

And it error'd out with:

```
Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/RsaCtfTool.py", line 502, in <module>
    main()
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/RsaCtfTool.py", line 496, in main
    args = run_attacks(args, logger)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/RsaCtfTool.py", line 237, in run_attacks
    attackobj.attack_single_key(priv_key, selected_attacks)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 322, in attack_single_key
    % (attack_module.get_name(), self.publickey.filename)
AttributeError: 'PrivateKey' object has no attribute 'filename'
```
This is a test case, and it can be solved via Pollard's p-1 factoring with the gmpy library to generate one of the primes, so this case should run without issue and successfully decrypt the ciphertext
```
import gmpy2
q = primefac.pollard_pm1(n)
```

**Comment by daedalus** [comment]
I think the path code for direct modulus factorization is broken.
Please try
```
./RsaCtfTool.py --createpub -n <your modulus> -e 65537 > tmp.pub
./RsaCtfTool.py --publickey tmp.pub 
```

**Comment by johntrigg** [comment]
Ran the commands provided

```
python RsaCtfTool.py --createpub -n 14984962198660063864382329332414420640383401076210940326970380580002686792787549841757826322207380228475709831526150079054985643220286460040858635679099522461047125435547179836262035088538613643864726343947555810131214032176684953210400649987009365195363305448984625056469651901622510492256805277916429238237678991624609211686866220638957573492408427673564762335476393937949771790288899651982610955789425606231334241253290222180270938067127910825221018045967093881137664435200297802313731449759678431791478785781663312163425434957456894805128431979105321354657985616047053485527175910574195011390399363690121273756133 -e 65537 > tmp.pub
```

```
cat tmp.pub 
```
gives
```
-----BEGIN PUBLIC KEY-----
MIIBITANBgkqhkiG9w0BAQEFAAOCAQ4AMIIBCQKCAQB2tCoATJ1Zl1iqROEhLXL7
t74ubdjONNDJzf01fDjTo8h53j+w876JzcSg8GgO07HM1F9ryC5xTH4MlFSwJQBS
HL2M5ZvY0c2vV9cCr2waj8HJFeXwwBqnkInw9tJYgXc+CS0lNNPgNG4KjVXIoiyq
OzTns4yicwcPbStmDVwIPt4Al05srqk9/5h98Z6sxtha5Bllvoki8urx8VW1FhCC
EEZJvoeMEOKLc74L1SNTgA/oY5wWn8AxwspjAb49B3VAu0zIRLvIIjF7Aospau1f
972cLVEAIXlMEUOB8SauF1PF+8cB7Sp7nT6AZfOiFxbovXDAnHvF2UBxAoI2c0nl
AgMBAAE=
```
```python RsaCtfTool.py --publickey tmp.pub```

When I run the program using the created tmp.pub public key as an input, I get the following output: (also, the process killed itself, for some reason. I do not think it finished running.


```
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key tmp.pub.
attack initialized...
attack initialized...
[*] Performing factordb attack on tmp.pub.
[!] Composite not in factordb, couldn't factorize...
[!] An exception has occurred during the attack. Please check your inputs.
[!] cannot unpack non-iterable NoneType object
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
TypeError: cannot unpack non-iterable NoneType object

[+] Time elapsed: 0.3216 sec.
[*] Performing fibonacci_gcd attack on tmp.pub.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9999/9999 [00:00<00:00, 65333.85it/s]
[+] Time elapsed: 0.1719 sec.
[*] Performing mersenne_primes attack on tmp.pub.
 29%|████████████████████████████████████▏                                                                                      | 15/51 [00:00<00:00, 359511.77it/s]
[+] Time elapsed: 0.0005 sec.
[*] Performing nonRSA attack on tmp.pub.
[+] Time elapsed: 0.0063 sec.
[*] Performing pastctfprimes attack on tmp.pub.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 113/113 [00:00<00:00, 775705.98it/s]
[+] Time elapsed: 0.0009 sec.
[*] Performing smallq attack on tmp.pub.
[+] Time elapsed: 0.3268 sec.
[*] Performing system_primes_gcd attack on tmp.pub.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7007/7007 [00:00<00:00, 616765.40it/s]
[+] Time elapsed: 0.0344 sec.
[*] Performing SQUFOF attack on tmp.pub.
[!] Timeout.
[+] Time elapsed: 60.0008 sec.
[*] Performing boneh_durfee attack on tmp.pub.
[+] Time elapsed: 3.1444 sec.
[*] Performing carmichael attack on tmp.pub.
[!] Timeout.
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/carmichael.py", line 38, in attack
    r = carmichael(publickey.n)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/carmichael.py", line 19, in carmichael
    r1 = powmod(a, f << 1, N)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/utils.py", line 200, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

[+] Time elapsed: 60.0114 sec.
[*] Performing classical_shor attack on tmp.pub.
[!] Timeout.
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/classical_shor.py", line 42, in attack
    publickey.p, publickey.q = shor(publickey.n)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/classical_shor.py", line 22, in shor
    ar = powmod(a, r, n)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/utils.py", line 200, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

[+] Time elapsed: 60.0017 sec.
[*] Performing comfact_cn attack on tmp.pub.
[+] Time elapsed: 0.0001 sec.
[*] Performing compositorial_pm1_gcd attack on tmp.pub.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9999/9999 [00:00<00:00, 12493.56it/s]
[+] Time elapsed: 0.8009 sec.
[*] Performing cube_root attack on tmp.pub.
[+] Time elapsed: 0.0001 sec.
[*] Performing ecm2 attack on tmp.pub.
[!] Timeout.
[+] Time elapsed: 60.0072 sec.
[*] Performing factor_2PN attack on tmp.pub.
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'PublicKey' object has no attribute 'p'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/factor_2PN.py", line 73, in attack
    if publickey.p is not None and publickey.q is not None:
AttributeError: 'PublicKey' object has no attribute 'p'

[+] Time elapsed: 0.0125 sec.
[*] Performing factorial_pm1_gcd attack on tmp.pub.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 29998/29998 [00:08<00:00, 3453.18it/s]
[+] Time elapsed: 8.6879 sec.
[*] Performing fermat attack on tmp.pub.
[!] Timeout.
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/fermat.py", line 33, in attack
    publickey.p, publickey.q = fermat(publickey.n)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/fermat.py", line 18, in fermat
    b2 += c
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/utils.py", line 200, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

[+] Time elapsed: 60.0011 sec.
[*] Performing fermat_numbers_gcd attack on tmp.pub.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:01<00:00, 22.73it/s]
[+] Time elapsed: 1.2405 sec.
[*] Performing hart attack on tmp.pub.
[!] Timeout.
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/hart.py", line 34, in attack
    publickey.p, publickey.q = hart(publickey.n)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/hart.py", line 19, in hart
    m = pow(s, 2, N)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/utils.py", line 200, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

[+] Time elapsed: 60.0012 sec.
[*] Performing highandlowbitsequal attack on tmp.pub.
[+] Time elapsed: 0.0001 sec.
[*] Performing kraitchik attack on tmp.pub.
[!] Timeout.
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/kraitchik.py", line 35, in attack
    publickey.p, publickey.q = kraitchik(publickey.n)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/kraitchik.py", line 14, in kraitchik
    s = x * x - k * n
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/utils.py", line 200, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

[+] Time elapsed: 60.0009 sec.
[*] Performing lattice attack on tmp.pub.
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'PublicKey' object has no attribute 'p'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/lattice.py", line 23, in attack
    str(publickey.p),
AttributeError: 'PublicKey' object has no attribute 'p'

[+] Time elapsed: 0.0004 sec.
[*] Performing lehman attack on tmp.pub.
[!] Timeout.
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/lehman.py", line 41, in attack
    r = lehman(publickey.n)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/lehman.py", line 24, in lehman
    b2 = (a * a) - nk4
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/utils.py", line 200, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

[+] Time elapsed: 60.0017 sec.
[*] Performing lehmer attack on tmp.pub.
[!] Timeout.
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/lehmer.py", line 31, in attack
    publickey.p, publickey.q = lehmer_machine(publickey.n)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/lehmer.py", line 17, in lehmer_machine
    while not is_square(n + y * y):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/utils.py", line 200, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

[+] Time elapsed: 60.0013 sec.
[*] Performing mersenne_pm1_gcd attack on tmp.pub.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2045/2045 [00:00<00:00, 60019.25it/s]
[+] Time elapsed: 0.0348 sec.
[*] Performing noveltyprimes attack on tmp.pub.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 21/21 [00:00<00:00, 404038.46it/s]
[+] Time elapsed: 0.0005 sec.
[*] Performing partial_d attack on tmp.pub.
[!] partial_d attack is only for partial private keys not pubkeys...
[!] partial_d internal error...
[+] Time elapsed: 0.0002 sec.
[*] Performing partial_q attack on tmp.pub.
[!] partial_q attack is only for partial private keys not pubkeys...
[+] Time elapsed: 0.0001 sec.
[*] Performing pisano_period attack on tmp.pub.
[+] Time elapsed: 0.0001 sec.
[*] Performing pollard_p_1 attack on tmp.pub.
  2%|██▊                                                                                                                           | 22/997 [00:59<44:19,  2.73s/it][!] Timeout.
  2%|██▊                                                                                                                           | 22/997 [00:59<44:18,  2.73s/it]
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/pollard_p_1.py", line 42, in attack
    poll_res = pollard_P_1(publickey.n, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/pollard_p_1.py", line 24, in pollard_P_1
    p = gcd(n, powmod(pp, z[i], n) - 1)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/utils.py", line 200, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

[+] Time elapsed: 60.0012 sec.
[*] Performing primorial_pm1_gcd attack on tmp.pub.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10000/10000 [00:01<00:00, 9287.65it/s]
[+] Time elapsed: 1.0772 sec.
[*] Performing qicheng attack on tmp.pub.
[+] Time elapsed: 30.6756 sec.
[*] Performing qs attack on tmp.pub.
[!] Timeout.
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/qs.py", line 24, in attack
    subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1981, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/utils.py", line 200, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

[+] Time elapsed: 60.0065 sec.
[*] Performing siqs attack on tmp.pub.
Can't load siqs because yafu binary is not installed
[*] Performing small_crt_exp attack on tmp.pub.
[!] Timeout.
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/small_crt_exp.py", line 20, in attack
    subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1981, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/utils.py", line 200, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

[+] Time elapsed: 60.0040 sec.
[*] Performing wiener attack on tmp.pub.
 17%|█████████████████████▏                                                                                                         | 2/12 [00:00<00:00, 348.74it/s]
[!] An exception has occurred during the attack. Please check your inputs.
[!] isqrt() of negative number
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/wiener.py", line 37, in attack
    pq = wiener(publickey.n, publickey.e, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/wiener.py", line 25, in wiener
    pq = trivial_factorization_with_n_phi(n, phi)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/number_theory.py", line 418, in trivial_factorization_with_n_phi
    i = isqrt(pow(m, 2) - (N << 2))  # same as isqrt((m**2) - (4*n))
ValueError: isqrt() of negative number

[+] Time elapsed: 0.0085 sec.
[*] Performing wolframalpha attack on tmp.pub.
[*] Performing z3_solver attack on tmp.pub.
[!] Timeout.
[+] Time elapsed: 60.2650 sec.
[*] Performing XYXZ attack on tmp.pub.
[+] Time elapsed: 20.4281 sec.
[*] Performing binary_polinomial_factoring attack on tmp.pub.
[+] Time elapsed: 2.3167 sec.
[*] Performing brent attack on tmp.pub.
[!] Timeout.
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/brent.py", line 62, in attack
    poll_res = brent(publickey.n)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/brent.py", line 30, in brent
    y = (powmod(y, 2, N) + c) % N
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/utils.py", line 200, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

[+] Time elapsed: 60.0278 sec.
[*] Performing cm_factor attack on tmp.pub.
 17%|█████████████████████▌                                                                                                           | 1/6 [00:01<00:07,  1.52s/it][!] Timeout.
 17%|█████████████████████▌                                                                                                           | 1/6 [01:00<05:00, 60.00s/it]
[!] An exception has occurred during the attack. Please check your inputs.
[!] 'Timer expired'
[!] Traceback (most recent call last):
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/rsa_attack.py", line 328, in attack_single_key
    self.priv_key, unciphered = attack_module.attack_wrapper(
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/abstract_attack.py", line 44, in attack_wrapper
    return self.attack(publickeys, cipher, progress)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/attacks/single_key/cm_factor.py", line 23, in attack
    sageresult = subprocess.check_output(
  File "/usr/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.9/subprocess.py", line 507, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1134, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "/usr/lib/python3.9/subprocess.py", line 1981, in _communicate
    ready = selector.select(timeout)
  File "/usr/lib/python3.9/selectors.py", line 416, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/mandate/Desktop/hackabull/crypto/RsaCtfTool/lib/utils.py", line 200, in _timeout_handler
    raise TimeoutError(self.timeout_message)
lib.utils.TimeoutError: 'Timer expired'

[+] Time elapsed: 60.0133 sec.
[*] Performing dixon attack on tmp.pub.
[-] Dixon is too slow for pubkeys > 10^10...
[+] Time elapsed: 0.0003 sec.
[*] Performing ecm attack on tmp.pub.
[!] Timeout.
[+] Time elapsed: 60.0077 sec.
[*] Performing euler attack on tmp.pub.
[!] Timeout.
[+] Time elapsed: 60.0010 sec.
[*] Performing londahl attack on tmp.pub.
 59%|███████████████████████████████████████████████████████████████████▏                                             | 5947974/10000001 [00:17<03:18, 20433.22it/s]
Killed
```
