### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by skr3wfac3** [RsaCtfTool/RsaCtfTool#426]
When running the command: `./RsaCtfTool.py --publickey key.pub --uncipherfile flag.enc --private` on a Kali box, I get the following output:

['key.pub']`

[*] Testing key key.pub.
Traceback (most recent call last):
  File "/home/kali/Desktop/HTB/WeakRSA/RsaCtfTool/./RsaCtfTool.py", line 544, in <module>
    main()
  File "/home/kali/Desktop/HTB/WeakRSA/RsaCtfTool/./RsaCtfTool.py", line 537, in main
    args = run_attacks(args, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/HTB/WeakRSA/RsaCtfTool/./RsaCtfTool.py", line 262, in run_attacks
    attackobj.attack_single_key(publickey, selected_attacks)
  File "/home/kali/Desktop/HTB/WeakRSA/RsaCtfTool/lib/rsa_attack.py", line 264, in attack_single_key
    self.load_attacks(attacks_list)
  File "/home/kali/Desktop/HTB/WeakRSA/RsaCtfTool/lib/rsa_attack.py", line 163, in load_attacks
    attack_module = importlib.import_module(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1074, in get_code
  File "<frozen importlib._bootstrap_external>", line 1004, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kali/Desktop/HTB/WeakRSA/RsaCtfTool/attacks/single_key/classical_shor.py", line 20
    g = gcd(n, a): # a `should` be coprime of n otherwise it is a trivial factor of n.
                        ^
SyntaxError: invalid syntax

**Comment by daedalus** [comment]
should be ok
