### ISSUE TITLE
Cache decorator breaks common_factors attack on python 3.10+

### ISSUE THREAD

**Issue by joonatanjak** [RsaCtfTool/RsaCtfTool#465]
The common_factors attack is no longer working with python3.10 and onward.

```python3
$ python3.10 ./RsaCtfTool.py --publickey "examples/commonfactor?.pub" --private --attack common_factors
['examples/commonfactor1.pub', 'examples/commonfactor3.pub', 'examples/commonfactor2.pub', 'examples/commonfactor6.pub', 'examples/commonfactor7.pub', 'examples/commonfactor5.pub', 'examples/commonfactor4.pub', 'examples/commonfactor9.pub', 'examples/commonfactor8.pub']
[*] Multikey mode using keys: examples/commonfactor1.pub, examples/commonfactor3.pub, examples/commonfactor2.pub, examples/commonfactor6.pub, examples/commonfactor7.pub, examples/commonfactor5.pub, examples/commonfactor4.pub, examples/commonfactor9.pub, examples/commonfactor8.pub
[*] Performing common_factors attack.
Traceback (most recent call last):
  File "/private/tmp/RsaCtfTool/./RsaCtfTool.py", line 577, in <module>
    main()
  File "/private/tmp/RsaCtfTool/./RsaCtfTool.py", line 569, in main
    args = run_attacks(args, logger)
  File "/private/tmp/RsaCtfTool/./RsaCtfTool.py", line 250, in run_attacks
    found = attackobj.attack_multiple_keys(args.publickey, selected_attacks)
  File "/private/tmp/RsaCtfTool/lib/rsa_attack.py", line 222, in attack_multiple_keys
    self.priv_key, decrypted = attack_module.attack(
  File "/private/tmp/RsaCtfTool/attacks/multi_keys/common_factors.py", line 22, in attack
    M = list_prod(pubs)
TypeError: unhashable type: 'list'
```

The issue appears to be with the `@cache` decorator for the `list_prod` function, which attempts to cache a list:
https://github.com/RsaCtfTool/RsaCtfTool/blob/b36adb34382ae8f7f57fb5a627fbc10c9defc946/lib/number_theory.py#L32-L37

As a temporary fix, one could just remove the decorator from that function and the code will work again.

**Comment by daedalus** [comment]
lists are not hashable types beacuse they are mutable but tuples are inmutable therefore hashable.
