### ISSUE TITLE
--decrypt not working(ValueError: invalid literal for int() with base 10)

### ISSUE THREAD

**Issue by DarthVesko** [RsaCtfTool/RsaCtfTool#475]
I'm doing a ctf where I have to decrypt a cyphertext from a public key, and I am running the following command:

`rsactf --publickey pubkey.pem --decrypt e8oQDihsmkvjT3sZe+EE8lwNvBEsFegYF6+OOFOiR6gMtMZxxba/bIgLUD8pV3yEf0gOOfHuB5bC3vQmo7bE4PcIKfpFGZBA --private`

This outputs the following error:

```
Traceback (most recent call last):
  File "/home/kali/.local/bin/rsactf", line 585, in <module>
    main()
  File "/home/kali/.local/bin/rsactf", line 475, in main
    decrypt = get_numeric_value(decrypt)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/rsactf/lib/utils.py", line 25, in get_numeric_value
    return int(value, 16) if value.startswith("0x") else int(value)
                                                         ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'e8oQDihsmkvjT3sZe+EE8lwNvBEsFegYF6+OOFOiR6gMtMZxxba/bIgLUD8pV3yEf0gOOfHuB5bC3vQmo7bE4PcIKfpFGZBA'
```

However, when I paste the string in a file and then run `--decryptfile` on said file, it works.

**Comment by daedalus** [comment]
can you share your public.pem for testing?

**Comment by redtrib3** [comment]
get_numeric_value() expects hex or integer in line 475 - RsaCtfTool.py 
```
   472	    if args.decrypt is not None:
   473	        decrypt_array = []
   474	        for decrypt in args.decrypt.split(","):
   475	            decrypt = get_numeric_value(decrypt)    <---- entrypoint
   476	            decrypt = get_base64_value(decrypt)
   477	            decrypt_array.append(n2s(decrypt))
   478	        args.decrypt = decrypt_array

```

```
def get_numeric_value(value):
    return int(value, 16) if value.startswith("0x") else int(value) <--- error
```
@daedalus

**Comment by daedalus** [comment]
I'm closing this since there was no further activity.
